language: python

python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8

install:
  - pip install -U pip
  - pip install --no-cache-dir -r requirements.txt -r requirements-dev.txt
  - pip install -U codecov

script:
  - bash ci.bash

after_success:
  - codecov
